name: /home/kkladny/anaconda3/envs/confgen
channels:
  - conda-forge
dependencies:
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fcd-torch==1.0.7
      - filelock==3.13.4
      - fonttools==4.51.0
      - fpsample==0.3.2
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.62.2
      - hydra-core==1.3.2
      - idna==3.7
      - imageio==2.34.2
      - jinja2==3.1.3
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - llvmlite==0.43.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - normflows==1.7.3
      - nose==1.3.7
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - overrides==7.7.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pip==24.0
      - pomegranate==1.1.0
      - protobuf==5.26.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - rdkit==2023.9.6
      - requests==2.32.3
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - tikzplotlib==0.10.1
      - torch==2.3.0
      - torch-geometric==2.5.3
      - torchmetrics==1.3.2
      - torchvision==0.18.0
      - tqdm==4.66.2
      - triton==2.3.0
      - tzdata==2024.1
      - ucimlrepo==0.0.7
      - urllib3==2.2.2
      - wandb==0.17.3
      - webcolors==1.11
      - werkzeug==3.0.2
      - yarl==1.9.4
